LIB = \
src/antlr4-runtime-cpp/InputMismatchException.o \
src/antlr4-runtime-cpp/BaseErrorListener.o \
src/antlr4-runtime-cpp/RuleContextWithAltNum.o \
src/antlr4-runtime-cpp/Exceptions.o \
src/antlr4-runtime-cpp/RuntimeMetaData.o \
src/antlr4-runtime-cpp/DefaultErrorStrategy.o \
src/antlr4-runtime-cpp/ConsoleErrorListener.o \
src/antlr4-runtime-cpp/ANTLRFileStream.o \
src/antlr4-runtime-cpp/UnbufferedTokenStream.o \
src/antlr4-runtime-cpp/ParserInterpreter.o \
src/antlr4-runtime-cpp/BufferedTokenStream.o \
src/antlr4-runtime-cpp/TokenStreamRewriter.o \
src/antlr4-runtime-cpp/Recognizer.o \
src/antlr4-runtime-cpp/Vocabulary.o \
src/antlr4-runtime-cpp/dfa/DFA.o \
src/antlr4-runtime-cpp/dfa/LexerDFASerializer.o \
src/antlr4-runtime-cpp/dfa/DFAState.o \
src/antlr4-runtime-cpp/dfa/DFASerializer.o \
src/antlr4-runtime-cpp/ProxyErrorListener.o \
src/antlr4-runtime-cpp/LexerInterpreter.o \
src/antlr4-runtime-cpp/ANTLRInputStream.o \
src/antlr4-runtime-cpp/IntStream.o \
src/antlr4-runtime-cpp/LexerNoViableAltException.o \
src/antlr4-runtime-cpp/misc/Interval.o \
src/antlr4-runtime-cpp/misc/IntervalSet.o \
src/antlr4-runtime-cpp/misc/MurmurHash.o \
src/antlr4-runtime-cpp/ParserRuleContext.o \
src/antlr4-runtime-cpp/TokenStream.o \
src/antlr4-runtime-cpp/Lexer.o \
src/antlr4-runtime-cpp/ListTokenSource.o \
src/antlr4-runtime-cpp/FailedPredicateException.o \
src/antlr4-runtime-cpp/Parser.o \
src/antlr4-runtime-cpp/RecognitionException.o \
src/antlr4-runtime-cpp/atn/LexerPopModeAction.o \
src/antlr4-runtime-cpp/atn/RuleStartState.o \
src/antlr4-runtime-cpp/atn/LexerATNConfig.o \
src/antlr4-runtime-cpp/atn/SingletonPredictionContext.o \
src/antlr4-runtime-cpp/atn/StarLoopbackState.o \
src/antlr4-runtime-cpp/atn/LookaheadEventInfo.o \
src/antlr4-runtime-cpp/atn/AbstractPredicateTransition.o \
src/antlr4-runtime-cpp/atn/AtomTransition.o \
src/antlr4-runtime-cpp/atn/PredictionMode.o \
src/antlr4-runtime-cpp/atn/ATNDeserializationOptions.o \
src/antlr4-runtime-cpp/atn/BasicState.o \
src/antlr4-runtime-cpp/atn/Transition.o \
src/antlr4-runtime-cpp/atn/ProfilingATNSimulator.o \
src/antlr4-runtime-cpp/atn/LexerModeAction.o \
src/antlr4-runtime-cpp/atn/PlusLoopbackState.o \
src/antlr4-runtime-cpp/atn/ParserATNSimulator.o \
src/antlr4-runtime-cpp/atn/LL1Analyzer.o \
src/antlr4-runtime-cpp/atn/ATNSerializer.o \
src/antlr4-runtime-cpp/atn/AmbiguityInfo.o \
src/antlr4-runtime-cpp/atn/LexerATNSimulator.o \
src/antlr4-runtime-cpp/atn/WildcardTransition.o \
src/antlr4-runtime-cpp/atn/EmptyPredictionContext.o \
src/antlr4-runtime-cpp/atn/LexerCustomAction.o \
src/antlr4-runtime-cpp/atn/DecisionEventInfo.o \
src/antlr4-runtime-cpp/atn/BlockEndState.o \
src/antlr4-runtime-cpp/atn/RuleStopState.o \
src/antlr4-runtime-cpp/atn/SetTransition.o \
src/antlr4-runtime-cpp/atn/ATNSimulator.o \
src/antlr4-runtime-cpp/atn/OrderedATNConfigSet.o \
src/antlr4-runtime-cpp/atn/LexerActionExecutor.o \
src/antlr4-runtime-cpp/atn/RuleTransition.o \
src/antlr4-runtime-cpp/atn/PredictionContext.o \
src/antlr4-runtime-cpp/atn/PredicateEvalInfo.o \
src/antlr4-runtime-cpp/atn/ATNDeserializer.o \
src/antlr4-runtime-cpp/atn/EpsilonTransition.o \
src/antlr4-runtime-cpp/atn/ParseInfo.o \
src/antlr4-runtime-cpp/atn/ArrayPredictionContext.o \
src/antlr4-runtime-cpp/atn/ATNConfigSet.o \
src/antlr4-runtime-cpp/atn/DecisionInfo.o \
src/antlr4-runtime-cpp/atn/ErrorInfo.o \
src/antlr4-runtime-cpp/atn/PlusBlockStartState.o \
src/antlr4-runtime-cpp/atn/LexerPushModeAction.o \
src/antlr4-runtime-cpp/atn/DecisionState.o \
src/antlr4-runtime-cpp/atn/ATNState.o \
src/antlr4-runtime-cpp/atn/TokensStartState.o \
src/antlr4-runtime-cpp/atn/LexerSkipAction.o \
src/antlr4-runtime-cpp/atn/LexerTypeAction.o \
src/antlr4-runtime-cpp/atn/PrecedencePredicateTransition.o \
src/antlr4-runtime-cpp/atn/ATNConfig.o \
src/antlr4-runtime-cpp/atn/StarLoopEntryState.o \
src/antlr4-runtime-cpp/atn/NotSetTransition.o \
src/antlr4-runtime-cpp/atn/SemanticContext.o \
src/antlr4-runtime-cpp/atn/LexerIndexedCustomAction.o \
src/antlr4-runtime-cpp/atn/LoopEndState.o \
src/antlr4-runtime-cpp/atn/LexerMoreAction.o \
src/antlr4-runtime-cpp/atn/ATN.o \
src/antlr4-runtime-cpp/atn/StarBlockStartState.o \
src/antlr4-runtime-cpp/atn/PredicateTransition.o \
src/antlr4-runtime-cpp/atn/LexerChannelAction.o \
src/antlr4-runtime-cpp/atn/BasicBlockStartState.o \
src/antlr4-runtime-cpp/atn/ActionTransition.o \
src/antlr4-runtime-cpp/atn/RangeTransition.o \
src/antlr4-runtime-cpp/atn/ContextSensitivityInfo.o \
src/antlr4-runtime-cpp/CommonToken.o \
src/antlr4-runtime-cpp/CommonTokenStream.o \
src/antlr4-runtime-cpp/InterpreterRuleContext.o \
src/antlr4-runtime-cpp/DiagnosticErrorListener.o \
src/antlr4-runtime-cpp/CommonTokenFactory.o \
src/antlr4-runtime-cpp/BailErrorStrategy.o \
src/antlr4-runtime-cpp/support/guid.o \
src/antlr4-runtime-cpp/support/CPPUtils.o \
src/antlr4-runtime-cpp/support/StringUtils.o \
src/antlr4-runtime-cpp/support/Arrays.o \
src/antlr4-runtime-cpp/UnbufferedCharStream.o \
src/antlr4-runtime-cpp/RuleContext.o \
src/antlr4-runtime-cpp/NoViableAltException.o \
src/antlr4-runtime-cpp/tree/ErrorNodeImpl.o \
src/antlr4-runtime-cpp/tree/TerminalNodeImpl.o \
src/antlr4-runtime-cpp/tree/ParseTree.o \
src/antlr4-runtime-cpp/tree/IterativeParseTreeWalker.o \
src/antlr4-runtime-cpp/tree/ParseTreeWalker.o \
src/antlr4-runtime-cpp/tree/Trees.o \
src/antlr4-runtime-cpp/tree/xpath/XPath.o \
src/antlr4-runtime-cpp/tree/xpath/XPathRuleElement.o \
src/antlr4-runtime-cpp/tree/xpath/XPathWildcardElement.o \
src/antlr4-runtime-cpp/tree/xpath/XPathTokenAnywhereElement.o \
src/antlr4-runtime-cpp/tree/xpath/XPathTokenElement.o \
src/antlr4-runtime-cpp/tree/xpath/XPathRuleAnywhereElement.o \
src/antlr4-runtime-cpp/tree/xpath/XPathWildcardAnywhereElement.o \
src/antlr4-runtime-cpp/tree/xpath/XPathElement.o \
src/antlr4-runtime-cpp/tree/xpath/XPathLexer.o \
src/antlr4-runtime-cpp/tree/xpath/XPathLexerErrorListener.o \
src/antlr4-runtime-cpp/tree/pattern/ParseTreePatternMatcher.o \
src/antlr4-runtime-cpp/tree/pattern/RuleTagToken.o \
src/antlr4-runtime-cpp/tree/pattern/ParseTreeMatch.o \
src/antlr4-runtime-cpp/tree/pattern/TagChunk.o \
src/antlr4-runtime-cpp/tree/pattern/TokenTagToken.o \
src/antlr4-runtime-cpp/tree/pattern/ParseTreePattern.o \
src/antlr4-runtime-cpp/tree/pattern/TextChunk.o \
src/antlr4-runtime-cpp/CharStream.o \


O = \
src/VerilogParser/Verilog2001BaseVisitor.o \
src/VerilogParser/Verilog2001Visitor.o \
src/VerilogParser/Verilog2001Parser.o \
src/VerilogParser/Verilog2001Lexer.o \
src/VhdlParser/vhdlLexer.o \
src/VhdlParser/vhdlVisitor.o \
src/VhdlParser/vhdlBaseVisitor.o \
src/VhdlParser/vhdlParser.o \
src/SVParser/sv2012Parser.o \
src/SVParser/sv2012Visitor.o \
src/SVParser/sv2012Lexer.o \
src/SVParser/sv2012BaseVisitor.o \
src/main.o src/convertor.o \
src/vhdlConvertor/packageParser.o \
src/vhdlConvertor/referenceParser.o \
src/vhdlConvertor/exprParser.o \
src/vhdlConvertor/entityParser.o \
src/vhdlConvertor/compInstanceParser.o \
src/vhdlConvertor/archParser.o \
src/vhdlConvertor/interfaceParser.o \
src/vhdlConvertor/statementParser.o \
src/vhdlConvertor/packageHeaderParser.o \
src/vhdlConvertor/literalParser.o \
src/vhdlConvertor/designFileParser.o \
src/verilogConvertor/utils.o \
src/verilogConvertor/portParser.o \
src/verilogConvertor/source_textParser.o \
src/verilogConvertor/exprParser.o \
src/verilogConvertor/moduleParser.o \
src/verilogConvertor/literalParser.o \
src/verilogConvertor/attributeParser.o \
src/baseHdlParser/baseHdlParser.o \
src/notImplementedLogger.o \
src/hdlObjects/operator.o \
src/hdlObjects/context.o \
src/hdlObjects/variable.o \
src/hdlObjects/function.o \
src/hdlObjects/entity.o \
src/hdlObjects/named.o \
src/hdlObjects/port.o \
src/hdlObjects/arch.o \
src/hdlObjects/jsonable.o \
src/hdlObjects/aPackage.o \
src/hdlObjects/statement.o \
src/hdlObjects/operatorType.o \
src/hdlObjects/compInstance.o \
src/hdlObjects/symbol.o \
src/hdlObjects/expr.o \
src/svConverter/library_textParser.o \

CPPFLAGS=-g -std=c++11 -Isrc/antlr4-runtime-cpp -Isrc -I/usr/include/python3.5m

hdlconv: $O $(LIB)
	g++ -o $@ $O $(LIB)

lib.a: $(LIB)
	ar rc lib.a $(LIB)
